[workspace]
authors = ["MoSafi2 <mohamed.mabrouk@rwth-aachen.de>"]
channels = ["conda-forge", "bioconda", "r"]
name = "DGEA_RNAseq"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]


[dependencies]
jupytext = ">=1.17.3,<2"
r-irkernel = ">=1.3.2,<2"
pixi-kernel = ">=0.6.6,<0.7"
r-essentials = ">=4.4,<5"
r-kableextra = ">=1.4.0,<2"
bioconductor-genomeinfodb = ">=1.42.0,<2"
bioconductor-deseq2 = ">=1.46.0,<2"
bioconductor-summarizedexperiment = ">=1.36.0,<2"
r-plotly = ">=4.11.0,<5"
r-viridis = ">=0.6.5,<0.7"
r-dt = ">=0.34.0,<0.35"
"r-data.table" = ">=1.17.8,<2"
bioconductor-tximport = ">=1.34.0,<2"
r-ggrepel = ">=0.9.6,<0.10"
r-openxlsx = ">=4.2.8,<5"
pandoc = ">=3.6.3,<4"
r-tidyverse = ">=2.0.0,<3"
r-quarto = ">=1.5.1,<2"
r-bitops = ">=1.0_9,<2"
r-pheatmap = ">=1.0.13,<2"
bioconductor-clusterprofiler = ">=4.14.0,<5"
bioconductor-enrichplot = ">=1.26.1,<2"
r-ggridges = ">=0.5.7,<0.6"
"bioconductor-org.mm.eg.db" = { version = ">=3.20.0,<4", channel = "bioconda" }
"bioconductor-org.hs.eg.db" = { version = ">=3.20.0,<4", channel = "bioconda" }
"bioconductor-go.db" = { version = ">=3.20.0,<4", channel = "bioconda" }

[pypi-dependencies]
quarto-cli = ">=1.8.25, <2"

